# Generated by Django 5.2.6 on 2025-10-02 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=16.0, help_text='VAT percentage (default 16%)', max_digits=5)),
                ('idf_rate', models.DecimalField(decimal_places=3, default=3.5, help_text='Import Declaration Fee percentage (default 3.5%)', max_digits=5)),
                ('rdl_rate', models.DecimalField(decimal_places=3, default=2.0, help_text='Road Development Levy percentage (default 2%)', max_digits=5)),
                ('estimated_clearing_agent_fee', models.DecimalField(decimal_places=2, default=20000, help_text='Estimated clearing agent fee in KES', max_digits=10)),
                ('estimated_port_handling', models.DecimalField(decimal_places=2, default=15000, help_text='Estimated port handling charges in KES', max_digits=10)),
                ('estimated_ntsa_inspection', models.DecimalField(decimal_places=2, default=5000, help_text='Estimated NTSA inspection fee in KES', max_digits=10)),
                ('estimated_registration', models.DecimalField(decimal_places=2, default=20000, help_text='Estimated registration and number plates in KES', max_digits=10)),
                ('estimated_transport', models.DecimalField(decimal_places=2, default=25000, help_text='Estimated transport from Mombasa in KES', max_digits=10)),
                ('current_year', models.IntegerField(default=2025)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Configuration',
                'verbose_name_plural': 'Tax Configuration',
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('PASSENGER_CAR_SMALL', 'Passenger Car ≤1500cc'), ('PASSENGER_CAR_MEDIUM', 'Passenger Car >1500cc'), ('PASSENGER_CAR_LARGE', 'Passenger Car >3000cc petrol / >2500cc diesel'), ('ELECTRIC_VEHICLE', '100% Electric Vehicle'), ('HYBRID_VEHICLE', 'Hybrid Vehicle'), ('BUS', 'Bus'), ('SCHOOL_BUS', 'School Bus (Public Schools)'), ('TRUCK', 'Truck/Lorry'), ('PRIME_MOVER', 'Prime Mover'), ('TRAILER', 'Trailer'), ('AMBULANCE', 'Ambulance'), ('MOTORCYCLE', 'Motorcycle'), ('SPECIAL_PURPOSE', 'Special Purpose Vehicle'), ('HEAVY_MACHINERY', 'Heavy Machinery')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('customs_factor', models.DecimalField(decimal_places=3, help_text='Factor to convert retail price to customs value (e.g., 0.426 for 42.6%)', max_digits=5)),
                ('import_duty_rate', models.DecimalField(decimal_places=2, help_text='Import duty percentage (e.g., 35.00 for 35%)', max_digits=5)),
                ('excise_duty_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Excise duty percentage (e.g., 20.00 for 20%)', max_digits=5, null=True)),
                ('excise_duty_fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed excise amount for motorcycles (KES)', max_digits=15, null=True)),
                ('exempt_import_duty', models.BooleanField(default=False)),
                ('exempt_excise_duty', models.BooleanField(default=False)),
                ('hs_codes', models.TextField(blank=True, help_text='Comma-separated HS codes (e.g., 8703.24.90, 8703.33.90)')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Vehicle Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('DIRECT', 'Direct Import'), ('PREVIOUSLY_REGISTERED', 'Previously Registered in Kenya')], max_length=25)),
                ('vehicle_age_years', models.IntegerField(help_text='Age of vehicle in years (e.g., 1, 2, 3...)')),
                ('depreciation_rate', models.DecimalField(decimal_places=2, help_text='Depreciation percentage (e.g., 20.00 for 20%)', max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['import_type', 'vehicle_age_years'],
                'unique_together': {('import_type', 'vehicle_age_years', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('vehicle_type', models.CharField(choices=[('VEHICLE', 'Car/Truck/Bus'), ('MOTORCYCLE', 'Motorcycle'), ('HEAVY_MACHINERY', 'Heavy Machinery')], max_length=20)),
                ('vehicle_id', models.IntegerField(blank=True, help_text='ID from vehicles app', null=True)),
                ('market_value_kes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('year_of_manufacture', models.IntegerField()),
                ('engine_capacity', models.IntegerField(blank=True, help_text='Engine in cc', null=True)),
                ('import_type', models.CharField(choices=[('DIRECT', 'Direct Import'), ('PREVIOUSLY_REGISTERED', 'Previously Registered')], max_length=25)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('vehicle_age', models.IntegerField()),
                ('depreciation_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('depreciated_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('customs_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('import_duty', models.DecimalField(decimal_places=2, max_digits=15)),
                ('excise_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('excise_duty', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=15)),
                ('idf', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rdl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('calculation_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='tax_calculator.vehiclecategory')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['calculation_id'], name='tax_calcula_calcula_34cdb1_idx'), models.Index(fields=['created_at'], name='tax_calcula_created_4d544a_idx'), models.Index(fields=['vehicle_type'], name='tax_calcula_vehicle_e0f621_idx')],
            },
        ),
    ]
