# Generated by Django 5.2.6 on 2025-09-28 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclemake')),
            ],
            options={
                'unique_together': {('make', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transmission', models.CharField(choices=[('AT', 'Automatic'), ('MT', 'Manual'), ('CVT', 'CVT'), ('AMT', 'Automated Manual')], max_length=10)),
                ('drive_configuration', models.CharField(choices=[('FWD', 'Front Wheel Drive'), ('RWD', 'Rear Wheel Drive'), ('4WD', 'Four Wheel Drive'), ('AWD', 'All Wheel Drive'), ('2WD', 'Two Wheel Drive')], max_length=10)),
                ('engine_capacity', models.CharField(max_length=50)),
                ('body_type', models.CharField(choices=[('SUV', 'SUV'), ('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatchback'), ('WAGON', 'Wagon'), ('S.WAGON', 'Station Wagon'), ('COUPE', 'Coupe'), ('CONVERTIBLE', 'Convertible'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('PICKUP', 'Pickup')], max_length=20)),
                ('gvw', models.CharField(blank=True, max_length=50, null=True)),
                ('seating', models.IntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('GASOLINE', 'Gasoline'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid'), ('PLUG-IN HYBRID', 'Plug-in Hybrid'), ('PETROL', 'Petrol')], max_length=20)),
                ('crsp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclemake')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclemodel')),
            ],
            options={
                'unique_together': {('make', 'model', 'model_number', 'transmission', 'drive_configuration')},
            },
        ),
    ]
