# Generated by Django 5.2.6 on 2025-10-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heavymachinery',
            name='horsepower',
            field=models.CharField(blank=True, help_text='Horsepower (leave empty if no engine)', max_length=50, null=True),
        ),
    ]
