# Generated by Django 5.2.6 on 2025-09-29 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('VEHICLE', 'Vehicle'), ('MOTORCYCLE', 'Motorcycle'), ('HEAVY_MACHINERY', 'Heavy Machinery')], max_length=20)),
                ('vehicle_id', models.IntegerField()),
                ('import_type', models.CharField(choices=[('DIRECT', 'Direct Import'), ('PREVIOUSLY_REGISTERED', 'Previously Registered in Kenya')], max_length=30)),
                ('year_of_manufacture', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('current_year', models.IntegerField()),
                ('original_crsp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('depreciated_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('customs_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('import_duty', models.DecimalField(decimal_places=2, max_digits=15)),
                ('excise_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('excise_duty', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rdl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('idf', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_taxes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calculation_reference', models.UUIDField(unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('VEHICLE_1500CC_BELOW', 'Vehicles ≤1500cc'), ('VEHICLE_ABOVE_1500CC', 'Vehicles >1500cc (Standard)'), ('VEHICLE_LUXURY', 'Luxury Vehicles (>3000cc petrol / >2500cc diesel)'), ('VEHICLE_ELECTRIC', '100% Electric Vehicles'), ('SCHOOL_BUS', 'School Buses for Public Schools'), ('PRIME_MOVER', 'Prime Movers'), ('TRAILER', 'Trailers'), ('AMBULANCE', 'Ambulances'), ('MOTORCYCLE', 'Motorcycles'), ('SPECIAL_PURPOSE', 'Special Purpose Vehicles'), ('HEAVY_MACHINERY', 'Heavy Machinery')], max_length=50, unique=True)),
                ('import_duty_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('excise_duty_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('excise_duty_fixed', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed excise duty amount (for motorcycles)', max_digits=15, null=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('customs_value_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of depreciated CRSP to calculate customs value', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='DepreciationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('DIRECT', 'Direct Import'), ('PREVIOUSLY_REGISTERED', 'Previously Registered in Kenya')], max_length=30)),
                ('years_from', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('years_to', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('depreciation_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'ordering': ['import_type', 'years_from'],
                'unique_together': {('import_type', 'years_from', 'years_to')},
            },
        ),
    ]
